project:
  type: website

website:
  title: "Federico Maioli"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: about.qmd
        text: CV


format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

