project:
  type: website
  output-dir: docs
website:
  title: "Federico Maioli"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: 'About'
      - href: about.qmd
        text: 'CV'
      - href: blog.qmd
        text: 'Blog'


format:
  html:
    page-layout: full 
    theme: flatly
    mainfont: 'Helvetica'
    fontsize: 1.3em
    linestretch: 1.3
    css: styles.css
    toc: true

editor: visual

